language: ruby

services:
  - docker

before_install:
  - docker pull wott/wott-io
  - docker build -t wott/wott-io .

script:
  - docker run -v $(pwd):/usr/src/app wott-io /bin/sh -c "jekyll build"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: ./_site
  on:
    branch: master
