language: ruby

services:
  - docker

before_install:
  - docker build -t wott-io .

script:
  - docker run wott-io /bin/sh -v $(pwd):/usr/src/app -c "jekyll build"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
