# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 100 # it will paginate after this number
language: 'en-uk'
words_per_minute: 200

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: '/'

# Website info
title: WOTT IO
description: The professional publishing platform
cover: assets/images/blog-cover.jpg
logo: assets/images/blog-icon.png
logo_dark: assets/images/favicon.png
favicon: assets/images/favicon.png

# Social info
navigation: True # show the navbar links
subscribers: True # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter: wott # replace by your username
facebook: wott # replace by your username

# Permalinks
permalink: /:title
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins_dir: [_plugins]
plugins: [jekyll-paginate, jekyll-feed]

feed:
  path: feed.xml