# Jekyll configuration
markdown: kramdown
highlighter: rouge
# paginate: 10 # amount of posts to show
# paginate_path: /page:num/
language: 'en-uk'

baseurl: '/'
url: 'https://wott.io'

# Website info
title: Web of Trusted Things
description: WoTT is a free, automated, open-source public key infrastructure for connected hardware
cover: assets/images/blog-cover.jpg
favicon: assets/images/favicon.png

#Need add your subscribe mailchimp link list
mailchimp-list: https://wott.us20.list-manage.com/subscribe/post?u=250c99a25b42ad842add5bf41&amp;id=ac12838d30

twitter: wottsecurity
facebook: wott # replace by your username
google_analytics: UA-134852372-1

# Permalinks
permalink: /blog/:categories/:year/:month/:day/:title

plugins_dir:
  - _plugins
plugins:
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-redirect-from

pagination:
  enabled: true
  per_page: 10
  title: ':title (page :num )'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2
    
    
autopages:
    enabled: true

    categories:
        layouts: 
        - 'category.html'
        title: ':cat'
        permalink: '/blog/:cat'

  # Collection pages, omit to disable
    collections:
  
    tags:
        layouts: 
        - 'tag.html'
        title: 'Tag [:tag]'
        permalink: '/tag/:tag'


assets:
  cdn:
    baseurl: false
    destination: false
    url: 'https://wott.io/assets'

feed:
  path: feed.xml

exclude:
  - docker-compose.yml
  - README.md
  - Gemfile*
